---

- name: clone pets repo
  git:
    repo: 'https://github.com/karlpokus/pets'
    dest: /home/{{ user }}/pets
    update: yes

- name: install deps
  npm:
    path: /home/{{ user }}/pets/src/web
    production: yes
    state: present
    #ci: yes // needs ansible 2.8

- name: Copy service file
  become: true
  template:
    src: roles/web/templates/web.service.j2
    dest: /etc/systemd/system/web.service
    mode: 0644
  tags:
    - update_conf

- name: Restart process and reload systemd
  become: true
  systemd:
    name: web
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags:
    - restart
    - update_conf
