version: '3'
services:
  mongo:
    image: mongo:4.0.3
    container_name: mongo
    volumes:
      - mongo:/data
      - ./mongo-seed.js:/docker-entrypoint-initdb.d/mongo-seed.js
    restart: always
  web:
    image: pokus2000/pets-web:v0.7.2
    container_name: web
    depends_on:
      - mongo
    env_file: ./src/web/.env
    environment: # overrides env_file
      MONGODB_HOST: mongo
      HTTP_HOST: 0.0.0.0
      SERVICE_PETS_HOST: pets
    ports:
      - 127.0.0.1:9012:9012
    restart: always
  pets:
    image: pokus2000/pets-service:v0.8.2
    container_name: pets
    depends_on:
      - mongo
    env_file: ./src/pets/.env
    environment: # overrides env_file
      MONGODB_HOST: mongo
      HTTP_HOST: 0.0.0.0
    ports:
      - 127.0.0.1:9013:9013
    restart: always
volumes:
  mongo:
