---

- name: add signing key
  become: true
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: add repo
  become: true
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    filename: elastic-7.x.list
    state: present

- name: install
  become: true
  apt:
    name: metricbeat
    update_cache: yes

- name: copy main configs
  become: true
  template:
    src: roles/metricbeat/templates/metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    mode: 0600
    owner: root
    force: yes

- name: copy system configs
  become: true
  template:
    src: roles/metricbeat/templates/system.yml.j2
    dest: /etc/metricbeat/modules.d/system.yml
    mode: 0644
    owner: root
    force: yes

- name: copy mongodb configs
  become: true
  template:
    src: roles/metricbeat/templates/mongodb.yml.j2
    dest: /etc/metricbeat/modules.d/mongodb.yml
    mode: 0644
    owner: root
  when: mongodb_host is defined

- name: remove disabled mongodb configs
  become: true
  file:
    path: /etc/metricbeat/modules.d/mongodb.yml.disabled
    state: absent
  when: mongodb_host is defined

- name: copy nginx configs
  become: true
  template:
    src: roles/metricbeat/templates/nginx.yml.j2
    dest: /etc/metricbeat/modules.d/nginx.yml
    mode: 0644
    owner: root
  when: nginx_host is defined

- name: remove disabled nginx configs
  become: true
  file:
    path: /etc/metricbeat/modules.d/nginx.yml.disabled
    state: absent
  when: nginx_host is defined

- name: Restart process and reload systemd
  become: true
  systemd:
    name: metricbeat
    enabled: yes
    state: restarted
    daemon_reload: yes
  tags:
    - restart
