---

- name: Install
  become: true
  apt:
    name: ufw
    update_cache: yes

- name: Allow ssh
  become: true
  ufw:
    rule: limit # rate limiter; ip will be blacklisted if 6+ failed connection attempts under 30 secs
    port: ssh
    proto: tcp
    state: enabled
