---

- name: add signing key
  become: true
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: add repo
  become: true
  apt_repository:
    repo: deb https://deb.nodesource.com/{{ nodejs_version }} stretch main
    filename: nodesource.list
    state: present

- name: install
  become: true
  apt:
    name: nodejs
    update_cache: yes
